# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  sync:
    strategy:
      matrix: 
        color: [pink, blue, purple]
        include:
          - color: pink
            regex_filter: ^abc*
            number: 123
          - color: blue 
            regex_filter: ^def*
            number: 456
          - color: purple
            regex_filter: ghi*
            number: 789
    runs-on: ubuntu-latest
    env:
      repo_type: private
      color_color: ${{ matrix.color }}
      repo_filter_regex: ${{ matrix.regex_filter }}
      config_number: ${{ matrix.number }}

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.

      - name: Echo matrix var
        run: echo ${{ env.color_color }} ${{ env.repo_filter_regex }} ${{ env.config_number }}
